from app.online.models import (
    DocumentChunk,
    GraphResult,
    ImageContent,
    RetrievedChunk,
    RetrievalSource,
    TableContent,
)

# ==========================================================
# DOCUMENT STORE (Mock MongoDB)
# ==========================================================

MOCK_DOCUMENTS = {
    "chunk_001": DocumentChunk(
        chunk_id="chunk_001",
        doc_id="boiler_manual",
        original_text="""
The Steam Drum separates steam from water using gravity.
The separated steam flows to the superheater.
""",
        tables=[
            TableContent(
                table_id="tbl_001",
                content="""
Pressure : 180 bar
Temperature : 540 C
""",
                summary="Operating parameters of the Steam Drum."
            )
        ],
        images=[
            ImageContent(
                image_id="img_001",
                image_path="images/steam_drum.png",
                summary="Steam Drum connected to the Boiler."
            )
        ],
        metadata={
            "page": 42,
            "section": "Steam Drum"
        }
    ),

    "chunk_002": DocumentChunk(
        chunk_id="chunk_002",
        doc_id="boiler_manual",
        original_text="""
The Economizer preheats feed water using waste flue gases,
thereby improving the overall thermal efficiency.
""",
        metadata={
            "page": 55,
            "section": "Economizer"
        }
    ),

    "chunk_003": DocumentChunk(
        chunk_id="chunk_003",
        doc_id="boiler_manual",
        original_text="""
The Boiler Feed Pump supplies high-pressure water
to the Steam Drum continuously.
""",
        metadata={
            "page": 18,
            "section": "Boiler Feed Pump"
        }
    ),

    "chunk_004": DocumentChunk(
        chunk_id="chunk_004",
        doc_id="boiler_manual",
        original_text="""
The Superheater increases the temperature
of saturated steam before it enters the turbine.
""",
        metadata={
            "page": 60,
            "section": "Superheater"
        }
    ),

    "chunk_005": DocumentChunk(
        chunk_id="chunk_005",
        doc_id="boiler_manual",
        original_text="""
The Boiler converts feed water into steam
using heat generated by fuel combustion.
""",
        metadata={
            "page": 12,
            "section": "Boiler"
        }
    ),
}

# ==========================================================
# VECTOR DATABASE (Mock Qdrant)
# ==========================================================

MOCK_RETRIEVAL_RESULTS = {

    "chunk_001": RetrievedChunk(
        chunk_id="chunk_001",
        doc_id="boiler_manual",
        score=0.97,
        source=RetrievalSource.VECTOR,
        text_summary="Steam Drum separates steam and water.",
        table_summary="Steam Drum operating parameters.",
        image_summary="Steam Drum connection diagram."
    ),

    "chunk_002": RetrievedChunk(
        chunk_id="chunk_002",
        doc_id="boiler_manual",
        score=0.94,
        source=RetrievalSource.VECTOR,
        text_summary="Economizer preheats feed water using flue gases."
    ),

    "chunk_003": RetrievedChunk(
        chunk_id="chunk_003",
        doc_id="boiler_manual",
        score=0.92,
        source=RetrievalSource.VECTOR,
        text_summary="Boiler Feed Pump supplies high-pressure water."
    ),

    "chunk_004": RetrievedChunk(
        chunk_id="chunk_004",
        doc_id="boiler_manual",
        score=0.91,
        source=RetrievalSource.VECTOR,
        text_summary="Superheater increases steam temperature."
    ),

    "chunk_005": RetrievedChunk(
        chunk_id="chunk_005",
        doc_id="boiler_manual",
        score=0.90,
        source=RetrievalSource.VECTOR,
        text_summary="Boiler converts water into steam."
    ),
}

# ==========================================================
# BM25 KEYWORD INDEX
# ==========================================================

MOCK_KEYWORDS = {

    "steam drum": ["chunk_001"],
    "drum": ["chunk_001"],

    "economizer": ["chunk_002"],

    "boiler feed pump": ["chunk_003"],
    "feed pump": ["chunk_003"],

    "superheater": ["chunk_004"],

    "boiler": [
        "chunk_001",
        "chunk_003",
        "chunk_005"
    ],

    "steam": [
        "chunk_001",
        "chunk_004",
        "chunk_005"
    ],

    "feed water": [
        "chunk_002",
        "chunk_003"
    ],
}

# ==========================================================
# ENTITY INDEX
# ==========================================================

MOCK_ENTITIES = {

    "Steam Drum": "chunk_001",

    "Economizer": "chunk_002",

    "Boiler Feed Pump": "chunk_003",

    "Superheater": "chunk_004",

    "Boiler": "chunk_005",
}

# ==========================================================
# KNOWLEDGE GRAPH (Mock Neo4j)
# ==========================================================

MOCK_GRAPH = {

    "Steam Drum": GraphResult(

        entities=[
            "Boiler",
            "Steam Drum",
            "Superheater"
        ],

        relationships=[
            "Boiler FEEDS Steam Drum",
            "Steam Drum SUPPLIES Superheater"
        ],

        chunk_ids=[
            "chunk_001",
            "chunk_004",
            "chunk_005"
        ]
    ),

    "Economizer": GraphResult(

        entities=[
            "Boiler Feed Pump",
            "Economizer",
            "Boiler"
        ],

        relationships=[
            "Boiler Feed Pump SUPPLIES Economizer",
            "Economizer IMPROVES Boiler Efficiency"
        ],

        chunk_ids=[
            "chunk_002",
            "chunk_003",
            "chunk_005"
        ]
    ),

    "Boiler": GraphResult(

        entities=[
            "Boiler",
            "Steam Drum",
            "Economizer",
            "Superheater"
        ],

        relationships=[
            "Boiler CONNECTS Steam Drum",
            "Boiler CONNECTS Economizer",
            "Boiler CONNECTS Superheater"
        ],

        chunk_ids=[
            "chunk_001",
            "chunk_002",
            "chunk_004",
            "chunk_005"
        ]
    )
}